### ISSUE TITLE
Downtime - Serverless Registry API - 8:23 - 28 AM EST

### ISSUE THREAD

**Issue by catvec** [kscout/site-reliability-engineering#5]
Alert fired:

```
[FIRING:2] Metrics target down (prod critical)
Alert: Metrics target down
Host: []]()
Description: A target which is scraped for metrics has not been reachable for at least 1 minute.
Maintainers:
Severity: critical
Labels:
   - alertname: Metrics target down
   - component: prometheus
   - env: prod
   - instance: 10.130.0.52:9090
   - job: observe
   - pod: prod-prometheus-7b8cd5c488-cspdj
   - severity: criticalAlert: Metrics target down
Host: []]()
Description: A target which is scraped for metrics has not been reachable for at least 1 minute.
Maintainers:
Severity: critical
Labels:
   - alertname: Metrics target down
   - component: app
   - env: prod
   - instance: 10.130.1.104:9180
   - job: ops-bot
   - pod: prod-ops-bot-5-p8l7z
   - severity: criticalAlert: Metrics target down
Host: []]()
Description: A target which is scraped for metrics has not been reachable for at least 1 minute.
Maintainers:
Severity: critical
Labels:
   - alertname: Metrics target down
   - component: app
   - env: prod
   - instance: 10.130.0.51:9090
   - job: serverless-registry-api
   - pod: prod-serverless-registry-api-1-sbhk7
   - severity: critical
```
